name: "ALKiln: Automated docassemble tests"
description: "Automatically test any docassemble interview in a any branch on your GitHub repository whenever you commit or push. See https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing."

inputs:
  SERVER_URL:
    description: 'The url of your docassemble server. This should be in your GitHub SECRETS or the SECRETS of your org.'
    required: true
  DOCASSEMBLE_DEVELOPER_API_KEY:
    description: 'API key of the testing account with developer permissions on your docassemble server.'
    required: true
  # This is necessary to test pre-releases at the very least. It does seem
  # strange considering we're controlling everything through the action, but
  # that actually doesn't touch the npm version that's pulled in.
  ALKILN_VERSION:
    description: 'Version of ALKiln to get from npm.'
    required: false
    default: '^5.0.0'
  MAX_SECONDS_FOR_SETUP:
    description: "Amount of time to give the Project to upload your package's GitHub code."
    required: false
  SERVER_RELOAD_TIMEOUT_SECONDS:
    description: "Max amount of time to give the server to reload if it needs to"
    required: false
    # no default to let the custom Scenario timeouts create the reload timeout

runs:
  using: "composite"
  steps:
    # Set environment variables
    - name: "ALKiln: Set environment variables"
      # Human-readable date/time:
      # https://www.shell-tips.com/linux/how-to-format-date-and-time-in-linux-macos-and-bash/#how-to-format-a-date-in-bash
      run: |
        echo "ARTIFACT_NAME=alkiln-$(date +'%Y-%m-%d at %Hh%Mm%Ss' -u)UTC" >> $GITHUB_ENV
        echo "REPO_URL=https://github.com/SuffolkLITLab/docassemble-AssemblyLine" >> $GITHUB_ENV
        echo "BRANCH_PATH=main" >> $GITHUB_ENV
        echo "BASE_URL=${{ inputs.SERVER_URL }}" >> $GITHUB_ENV
        echo "DOCASSEMBLE_DEVELOPER_API_KEY=${{ inputs.DOCASSEMBLE_DEVELOPER_API_KEY }}" >> $GITHUB_ENV
        echo "ALKILN_VERSION=${{ inputs.ALKILN_VERSION }}" >> $GITHUB_ENV
        echo "MAX_SECONDS_FOR_SETUP=${{ inputs.MAX_SECONDS_FOR_SETUP }}" >> $GITHUB_ENV
        echo "SERVER_RELOAD_TIMEOUT_SECONDS=${{ inputs.SERVER_RELOAD_TIMEOUT_SECONDS }}" >> $GITHUB_ENV
        echo "_ORIGIN=github" >> $GITHUB_ENV
      shell: bash
    - name: "ALKiln: confirm info"
      run: |
        echo -e "\nALKiln version is $ALKILN_VERSION\nRepo is $REPO_URL\nBranch ref is $BRANCH_PATH\nMAX_SECONDS_FOR_SETUP is $MAX_SECONDS_FOR_SETUP\nSERVER_RELOAD_TIMEOUT_SECONDS is $SERVER_RELOAD_TIMEOUT_SECONDS\n"
      shell: bash

    # Install node
    - name: "ALKiln: Install node packages"
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install ALKiln directly from npm
      run: |
        npm install -g github:SuffolkLITLab/ALKiln#start_server_take_2
      shell: bash

    # Run tests
    - name: "ALKiln: Install project dependencies on server"
      run: alkiln-startserver
      shell: bash
    #- name: "ALKiln: Create a Project and pull the package from GitHub"
    #  run: alkiln-setup
    #  shell: bash
    - name: "ALKiln: Run tests"
      if: ${{ success() }}
      run: alkiln-run ${{ github.event.inputs.tags && format('{0}', github.event.inputs.tags) }}
      shell: bash
    - run: echo -e "\n\n====ALKiln could not create a project on your server's testing account or pull your package into it. Check the messages above this line.\n\n"
      if: ${{ failure() }}
      shell: bash
    - name: "ALKiln: Delete project from docassemble test account"
      if: ${{ always() }}
      run: alkiln-takedown
      shell: bash
    
    # Upload artifacts that subscribers can download on the Actions summary page
    - name: "ALKiln: Upload artifacts folder"
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./alkiln-*

# ##################################
# # A developer's workflow should look similar to the below
# # In place of `uses: suffolkLITLab/ALKiln@v5`, they
# # might use another version.
#
# name: ALKiln v5 tests
# on:
#   push:
#   workflow_dispatch:
#     inputs:
#       tags:
#         description: 'Optional. Use a "tag expression" specify which tagged tests to run. See https://cucumber.io/docs/cucumber/api/#tag-expressions for syntax.'
#         default: ''
#
# jobs:
#
#   interview-testing:
#     runs-on: ubuntu-latest
#     name: Run interview tests
#     steps:
#       - uses: actions/checkout@v3
#       - name: Use ALKiln to run tests
#         uses: suffolkLITLab/ALKiln@v5
#         with:
#           SERVER_URL: "${{ secrets.SERVER_URL }}"
#           DOCASSEMBLE_DEVELOPER_API_KEY: "${{ secrets.DOCASSEMBLE_DEVELOPER_API_KEY }}"
#       - run: echo "Finished running ALKiln tests"
