name: GitHub server installation

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      tags:
        required: False
        description: 'Optional. Use a "tag expression" specify which tagged tests to run (https://cucumber.io/docs/cucumber/api/#tag-expressions)'
      show_docker_output:
        required: false
        default: false
        type: boolean
        description: 'Show the docker logs while building the GitHub server container. It will also save the docker log artifact. This might show sensitive config information.'
      #### Developer note: You can probably leave this out
      enable_tmate:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:

  github-server-tests:
    #### Developer note: If you have both `push` and `pull_request` in the
    #### `on` section (above), this avoids running double tests when someone
    #### on the team makes a pull request
    # 1: Trigger job on push or dispatch from this repository
    # 2: Trigger job on pull request from a fork
    if: (
          github.event_name != 'pull_request'
          && ! github.event.pull_request.head.repo.fork
        ) || (
          github.event_name == 'pull_request'
          && github.event.pull_request.head.repo.fork
        )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    #### Developer note: You can probably leave out these specific
    #### environment variables. You may not even need the `env`
    #### keyword or values at all. See
    #### https://assemblyline.suffolklitlab.org/docs/alkiln/writing#env-vars
    env:
      NORMAL_USER_EMAIL: alkiln@example.com
      NORMAL_USER_PASSWORD: User123^
      WRONG_EMAIL: wrong_email@example.com
      WRONG_PASSWORD: wrong_password
      INVALID_API_KEY: invalidAPIkey
      EMPTY_STRING: ""
      SECRET_VAR1: secret-var1-value
      SECRET_VAR2: secret-var2-value
      SECRET_FOR_MISSING_FIELD: secret for missing field
      
    steps:
      # Place the root directory in this branch to access
      # relative paths to action files
      - uses: actions/checkout@v4

      - name: "Run ALKiln tests"
        if: ${{ success() }}
        id: alkiln
        #### Developer note: you'll need to replace `uses: ./`
        #### with the path to ALKiln’s repository name and branch name. For example,
        #### for version 5, use the branch name `v5`: `uses: suffolkLITLab/ALKiln@v5`
        uses: ./
        #### Developer note: You can probably leave out this `env` section
        env:
          # Internal: docassemble changes sometimes break @a11y tests. That is
          # a da problem, not ours. We will trigger these tests manually when we
          # want to check up on this.
          ALKILN_TAG_EXPRESSION: "${{ (github.event.inputs.tags && format('{0}', github.event.inputs.tags)) || '(not @error) and (not @temp_error)' }}"
        with:
          #### Developer note: Required inputs. See
          #### https://assemblyline.suffolklitlab.org/docs/alkiln/writing/#sandbox-inputs
          SERVER_URL: "${{ steps.github_server.outputs.SERVER_URL }}"
          DOCASSEMBLE_DEVELOPER_API_KEY: "${{ steps.github_server.outputs.DOCASSEMBLE_DEVELOPER_API_KEY }}"
          INSTALL_METHOD: "server"
          #### Developer note: You can probably leave the rest out
          #### To learn more, see https://assemblyline.suffolklitlab.org/docs/alkiln/writing/#optional-inputs
          ALKILN_TAG_EXPRESSION: "${{ env.ALKILN_TAG_EXPRESSION }}"
          # ALKILN_VERSION: 
