name: "Validate log codes"

# Tests error, warning, info, success, and debug log codes to
# check for things like mistakes in the numbering of the codes.
# For example, duplicate code numbers or missing code numbers.

on:
  push:
  workflow_dispatch:

jobs:

  log-code-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    name: Validate log codes
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: which seq
      - name: "Make sure seq is installed"
        run: sudo apt-get update && sudo apt-get install -y coreutils
      - run: which seq
      - name: Debug with tmate session
        uses: mxschmitt/action-tmate@v3
      - run: npm install
      - run: npm run codes
